version: "3"
services:
  client:
    volumes:
      - .:/srv/rescue-client
    build: .
    image: rescue-client-image
    container_name: rescue-client-container
    ports:
      - "3000:3000"
    networks:
      - rescue-api_mynetwork
networks:
  rescue-api_mynetwork:
    external: true